<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel\Doctrine\Controller;

use MSBios\CPanel\Doctrine\Mvc\Controller\AbstractLazyActionController;

/**
 * Class LayoutController
 * @package MSBios\CPanel\Doctrine\Controller
 */
class LayoutController extends AbstractLazyActionController
{
    /**
     * @return string
     */
    public function getResourceId()
    {
        return \MSBios\CPanel\Controller\LayoutController::class;
    }

    public function indexAction()
    {
        return parent::indexAction()
            ->setTemplate('ms-bios/c-panel/layout/index');
    }

    public function addAction()
    {
        return parent::addAction(); // TODO: Change the autogenerated stub
    }

    public function editAction()
    {
        return parent::editAction(); // TODO: Change the autogenerated stub
    }

    public function dropAction()
    {
        return parent::dropAction(); // TODO: Change the autogenerated stub
    }

}