<?php
/**
 * @access protected
 * @author Judzhin Miles <info[woof-woof]msbios.com>
 */
namespace MSBios\CPanel;

/** @var array $page */
$page = $this->navigation()->findActive(Navigation\Sidebar::class);

/** @var \Zend\Navigation\Page\Mvc $current */
$current = $page['page'];

/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
?>

<div class="panel panel-flat">

    <div class="panel-body">

        <?= $this->form()->openTag($form->setAttributes([
            'class' => 'form-horizontal',
            'role' => 'form'
        ])); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('module')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter layout title')
                ]),
            'label' => $this->translate('Module'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('controller')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter Controller Name')
                ]),
            'label' => $this->translate('Controller'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('action')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter Controller Action')
                ]),
            'label' => $this->translate('Action'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('icon')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter Icon')
                ]),
            'label' => $this->translate('Icon'),
        ]); ?>

        <?= $this->partial('partial/element.phtml', [
            'element' => $form->get('title')
                ->setAttributes([
                    'required' => 'required',
                    'placeholder' => $this->translate('Enter layout title')
                ]),
            'label' => $this->translate('Title'),
        ]); ?>

        <div class="text-right">
            <button type="reset" class="btn btn-default">Reset</button>
            <button type="submit" class="btn btn-primary">
                Submit
                <i class="icon-arrow-right14 position-right"></i>
            </button>
        </div>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>